# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: OS X install and tips

# Short description (goes below the title; it will also be used in the RSS feed)
# description: This is a sample Jekyll Blog.

# Your name, as you want it to appear underneath each post and in the footer
author: Nicolas Brousse

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl: /osx-install-and-tips

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://nicolas-brousse.github.io/



#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: redcarpet

pygments: true

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

server: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude
# exclude:

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
